version: "3.7"
services:
  traefik:
    restart: always
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    env_file:
      - ./.env
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--global.sendAnonymousUsage=false"
      - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.https_fiestas_today.entrypoint=websecure"
      - "--certificatesresolvers.https_fiestas_today.acme.httpchallenge=true"
      - "--certificatesresolvers.https_fiestas_today.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.https_fiestas_today.acme.email=${EMAIL_CERBOT}"
      - "--certificatesresolvers.https_fiestas_today.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
      - "8081:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik

networks:
  traefik:
    name: traefik_primary
